### ISSUE TITLE
Split view naming

### ISSUE THREAD

**Issue by seadaisy** [embl-cba/fiji-plugin-bigDataProcessor2#83]
@tischi 
Issue: Is "split view" the right term and is it defined (see as well discussion in the google doc https://docs.google.com/document/d/1Vo-ogtA-jXYIbOSwm2Rx1t2CSd9nF9wP/)?
My suggestion would be: Changing the name of the menu **Correct Chromatic Shift** to **Channel Alignment** (we do a manual alignment) and to have two options underneath: from **Split Chip Acquisition** or from **Full Chip Acquisition**

**Comment by tischi** [comment]
That's a good idea!

To make it a bit simpler what about:

- Align Channels...
- Align Channels Split Chip...

**Comment by seadaisy** [comment]
**Thumbs up**
